FORMAT: 1A
HOST: http://example.com/api/v2

# phonebook
# Group phonebook

## Phonebook [/phonebook{?Authorization,title,firstname,lastname,email}]

### queryPhonebook [GET]
Returns list of entries matching the query
+ Parameters
    + Authorization (string)

    + title (string, optional)

    + firstname (string, optional)

    + lastname (sring, optional)

    + email (string, optional)


+ Response 200 (application/json)

    OK

    + Attributes (PhonebookEntries)

+ Response 401 

    User not authorized




## Phonebook [/phonebook{?Authorization}]

### create [POST]
Adds entry to phonebook
+ Parameters
	+ Authorization (string)


+ Request (application/json)
    + Attributes (PhonebookEntry)

+ Response 201 

    Created successfully

+ Response 401 

    User not authorized




## Phonebook Favorites [/phonebook/favorites{?Authorization}]

### getFavorites [GET]
Returns list of favorite entries
+ Parameters
	+ Authorization (string)


+ Response 200 (application/json)

    OK

    + Attributes (PhonebookEntries)

+ Response 401 

    User not authorized




## Phonebook Favorites By Id [/phonebook/favorites/{id}{?Authorization,setting}]

### setFavorite [POST]
Sets the favorite status of an entry in the phonebook
+ Parameters
    + Authorization (string)
    
    + id (number, required)
    
    + setting (string, optional)


+ Response 201

    Favorite set successfully

+ Response 400 

    Bad arguments

+ Response 401 

    User not authorized

+ Response 404 

    Entry not found for given ID




## Phonebook By Id [/phonebook/{id}{?Authorization}]

### getEntry [GET]
Returns entry with provided ID
+ Parameters
	+ Authorization (string)
    
    + id (number, required)


+ Response 200 (application/json)

    OK

    + Attributes (PhonebookEntry)

+ Response 401 

    User not authorized

+ Response 404 

    Entry not found for given ID



### update [PUT]
Updates an existing entry in the phonebook
+ Parameters
	+ Authorization (string)
    
    + id (number, required)


+ Request (application/json)
    + Attributes (PhonebookEntry)

+ Response 200 (application/json)

    OK

    + Attributes (PhonebookEntry)

+ Response 401 

    User not authorized

+ Response 404 

    Entry not found for given ID



### deleteEntry [DELETE]
Deletes an existing entry from the phonebook
+ Parameters
	+ Authorization (string)

+ Response 204

    OK

+ Response 401 

    User not authorized

+ Response 404 

    Entry not found for given ID





# Group user

## User [/user]

### createUser [POST]
Creates new user entry

+ Response 200 (application/json)

    successful operation

    + Attributes (UserEntry)



# Data Structures

## PhonebookEntry (object)


### Properties
+ `id` (number, optional) 
+ `title` (string, optional) 
+ `firstName` (string, optional) 
+ `lastName` (string, optional) 
+ `phoneNumber` (string, optional) 
+ `email` (string, optional) 
+ `favorite` (boolean, optional) 


## PhonebookEntries (object)


### Properties
+ `entries` (array[PhonebookEntry], optional) 


## UserEntry (object)


### Properties
+ `key` (string, optional) 

