FORMAT: 1A
HOST: http://example.com/api/v2

# phonebook
# Group phonebook

## Phonebook [/phonebook{?Authorization,title,firstname,lastname,email}]

### queryPhonebook [GET]
Returns list of entries matching the query
+ Parameters
    + Authorization (string)
    + title (string, optional)
    + firstname (string, optional)
    + lastname (sring, optional)
    + email (string, optional)

+ Response 200 (application/json)
    + Attributes (PhonebookEntries)

+ Response 401 


## Phonebook [/phonebook{?Authorization}]

### create [POST]
Adds entry to phonebook
+ Parameters
    + Authorization (string)

+ Request (application/json)
    + Attributes (PhonebookEntry)

+ Response 201 

+ Response 401 

    
## Phonebook Favorites [/phonebook/favorites{?Authorization}]

### getFavorites [GET]
Returns list of favorite entries
+ Parameters
    + Authorization (string)

+ Response 200 (application/json)

    + Attributes (PhonebookEntries)

+ Response 401 


## Phonebook Favorites By Id [/phonebook/favorites/{id}{?Authorization,setting}]

### setFavorite [POST]
Sets the favorite status of an entry in the phonebook
+ Parameters
    + Authorization (string)  
    + id (number, required)
    + setting (string, optional)

+ Response 201

+ Response 400 

+ Response 401 

+ Response 404 


## Phonebook By Id [/phonebook/{id}{?Authorization}]

### getEntry [GET]
Returns entry with provided ID
+ Parameters
    + Authorization (string)
    + id (number, required)

+ Response 200 (application/json)
    + Attributes (PhonebookEntry)

+ Response 401 

+ Response 404 


### update [PUT]
Updates an existing entry in the phonebook
+ Parameters
    + Authorization (string)
    + id (number, required)

+ Request (application/json)
    + Attributes (PhonebookEntry)

+ Response 200 (application/json)
    + Attributes (PhonebookEntry)

+ Response 401 

+ Response 404 


### deleteEntry [DELETE]
Deletes an existing entry from the phonebook
+ Parameters
    + Authorization (string)

+ Response 204

+ Response 401 

+ Response 404 


# Group user

## User [/user]

### createUser [POST]
Creates new user entry

+ Response 200 (application/json)
    + Attributes (UserEntry)


# Data Structures

## PhonebookEntry (object)
+ id (number) 
+ title (string) 
+ firstName (string) 
+ lastName (string) 
+ phoneNumber (string) 
+ email (string) 
+ favorite (boolean) 


## PhonebookEntries (object)
+ entries (array[PhonebookEntry]) 


## UserEntry (object)
+ key (string) 

